- name: install user stuff
  hosts: all
  tasks:
    - name: Pull dotfiles
      ansible.builtin.git:
        repo: https://github.com/vmorganp/dotfiles
        dest: ~/dotfiles
        force: yes

    - name:  Remove stow files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~/.gitconfig
        - ~/.gitignore_global
        - ~/.nvimrc
        - ~/.config/nvim
        - ~/.zshrc

    - name: sync dotfiles
      shell: stow -d ~/dotfiles -t ~ git neovim tmux zsh

    - name: install neovim plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
