- name: install zsh
  hosts: all
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: change shell to zsh
      ansible.builtin.user:
        name: {{ username_on_the_host }}
        shell: /bin/zsh
        append: yes
      become: true

    - name:  delete oh-my-zsh
      file:
        path: ~/.oh-my-zsh
        state: absent

    - name: oh-my-zsh install
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
      args:
        creates: ~/.oh-my-zsh
