# Don't print a new line at the start of the prompt
add_newline = false
# palette = "gruvbox"

[directory]
style = "bg:blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
truncation_length = 10
truncation_symbol = ""
style = "bg:purple fg:black"

[git_status]

format = '($all_status$ahead_behind)'
conflicted = "[\\[CNFLCT\\]](bg:yellow fg:black)"
ahead = "[\\[AHEAD ${count}\\]](bg:yellow fg:black)"
behind = "[\\[BEHIND ${count}\\]](bg:yellow fg:black)"
diverged = "[DVRGD ${ahead_count}⇣${behind_count}](bg:yellow fg:black)"
up_to_date = "[\\[UP2DT\\]](bg:green fg:black)"
untracked = "[\\[UNTRCKD\\]](bg:red fg:black)"
stashed = "[\\[STSHD\\]](bg:yellow fg:black)"
modified = "[\\[CHGD\\]](bg:yellow fg:black)"
staged = '[\\[++\($count\)\\]](bg:green fg:black)'
renamed = "[\\[RNMD\\]](bg:yellow fg:black)"
deleted = "[\\[DLTD\\]](bg:yellow fg:black)"



# the aws module should be able to check if credentials are valid or not
# unfortunately it doesn't 
[aws]
disabled = true

[python]
format = "[$symbol(via $virtualenv)]($style)"
style = "bold bg:orange"


# Define custom colors
# [palettes.gruvbox]
# Overwrite existing color
# orange="#d65d0e"
