add_newline = false

[directory]
style = "bg:blue fg:bold black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
truncation_length = 10
truncation_symbol = ""
style = "bg:purple fg:bold black"

[git_status]
format = '($all_status$ahead_behind)'
conflicted = "[\\[CNFLCT\\]](bg:yellow fg:bold black)"
ahead = "[\\[AHEAD ${count}\\]](bg:yellow fg:bold black)"
behind = "[\\[BEHIND ${count}\\]](bg:yellow fg:bold black)"
diverged = "[DVRGD ${ahead_count}⇣${behind_count}](bg:yellow fg:bold black)"
up_to_date = "[\\[UP2DT\\]](bg:green fg:bold black)"
untracked = "[\\[UNTRCKD\\]](bg:red fg:bold black)"
stashed = "[\\[STSHD\\]](bg:yellow fg:bold black)"
modified = "[\\[CHGD\\]](bg:yellow fg:bold black)"
staged = '[\\[++\($count\)\\]](bg:green fg:bold black)'
renamed = "[\\[RNMD\\]](bg:yellow fg:bold black)"
deleted = "[\\[DLTD\\]](bg:yellow fg:bold black)"

# the aws module should be able to check if credentials are valid or not
# unfortunately it doesn't
[aws]
disabled = true

[python]
format = "[$symbol(via $virtualenv)]($style)"
style = "bold bg:orange"

